apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}
  namespace: demo-apps
  labels:
    app: {{ APP_NAME }}
    demo: "true"
    lifecycle: temporary
spec:
  type: ClusterIP
  selector:
    app: {{ APP_NAME }}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
